# Generated by Django 4.2.2 on 2023-06-07 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_option_answer_option_option1_option_option2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='emails',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
        migrations.AddField(
            model_name='option',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
