# Generated by Django 4.2.2 on 2023-06-07 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_remove_profile_emails_remove_profile_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='score',
        ),
        migrations.AddField(
            model_name='question',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
