# Generated by Django 4.2.2 on 2023-06-08 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_remove_option_score_question_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='option_text',
        ),
    ]
