# Generated by Django 4.2.2 on 2023-06-10 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_remove_option_option_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='score',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
