# Generated by Django 4.2.2 on 2023-06-12 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0009_alter_question_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='is_requested',
            field=models.BooleanField(default=False),
        ),
    ]
