# Generated by Django 4.2.2 on 2023-06-13 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exam', '0013_attemptquestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attempt',
            name='student',
        ),
        migrations.AddField(
            model_name='attemptquestion',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to=settings.AUTH_USER_MODEL),
        ),
    ]
