# Generated by Django 4.2.2 on 2023-06-13 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0014_remove_attempt_student_attemptquestion_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField()),
            ],
        ),
    ]
