# Generated by Django 4.2.2 on 2023-06-13 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0015_tempscore'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TempScore',
            new_name='TempSessionScore',
        ),
    ]
