# Generated by Django 4.2.2 on 2023-06-14 18:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("exam", "0017_question_subject"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attemptquestion",
            name="attempt",
        ),
    ]
