# Generated by Django 4.2.2 on 2023-06-14 19:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exam", "0018_remove_attemptquestion_attempt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attemptquestion",
            name="selected_option",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
