# Generated by Django 4.2.2 on 2023-06-14 19:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exam", "0019_alter_attemptquestion_selected_option"),
    ]

    operations = [
        migrations.AddField(
            model_name="attemptquestion",
            name="is_correct",
            field=models.BooleanField(default=False),
        ),
    ]
