# Generated by Django 4.2.2 on 2023-06-14 20:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exam", "0020_attemptquestion_is_correct"),
    ]

    operations = [
        migrations.AddField(
            model_name="attempt",
            name="is_attempted",
            field=models.BooleanField(default=False),
        ),
    ]
