# Generated by Django 4.2.2 on 2023-06-15 17:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exam", "0024_textexam_is_correct"),
    ]

    operations = [
        migrations.AddField(
            model_name="textexam",
            name="score",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="option",
            name="answer",
            field=models.CharField(
                blank=True,
                choices=[
                    (1, "Option 1"),
                    (2, "Option 2"),
                    (3, "Option 3"),
                    (4, "Option 4"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
