# Generated by Django 4.2.2 on 2023-06-15 18:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exam", "0026_alter_option_answer"),
    ]

    operations = [
        migrations.AddField(
            model_name="option",
            name="text_answer",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name="TextExam",
        ),
    ]
