# Generated by Django 4.2.2 on 2023-06-16 08:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exam", "0027_option_text_answer_delete_textexam"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="is_visible",
            field=models.BooleanField(default=False),
        ),
    ]
