# Generated by Django 4.2.2 on 2023-06-17 21:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exam", "0028_exam_is_visible"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exam",
            name="end_time",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name="exam",
            name="start_time",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("multiple_choice", "Multiple Choice"),
                    ("text_based", "Text Based"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="score",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
