# Generated by Django 4.2.2 on 2023-06-17 21:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("exam", "0029_alter_exam_end_time_alter_exam_start_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exam",
            name="end_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="exam",
            name="start_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
