# Generated by Django 4.2.2 on 2023-06-18 10:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exam", "0030_alter_exam_end_time_alter_exam_start_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="user_type",
            field=models.CharField(
                choices=[("Teacher", "Teacher"), ("Student", "Student")],
                default="Teacher",
                max_length=10,
            ),
        ),
    ]
