# Generated by Django 4.2.2 on 2023-06-18 10:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exam", "0031_alter_profile_user_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="user_type",
            field=models.CharField(
                choices=[("teacher", "Teacher"), ("student", "Student")], max_length=10
            ),
        ),
    ]
