# Generated by Django 4.2.2 on 2023-06-19 18:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exam", "0032_alter_profile_user_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attempt",
            name="score",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="option",
            name="option1",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name="option",
            name="option2",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name="option",
            name="option3",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name="option",
            name="option4",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name="option",
            name="text_answer",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="score",
            field=models.PositiveIntegerField(
                default=1, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name="tempsessionscore",
            name="score",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
