# Generated by Django 4.2.2 on 2023-06-19 18:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exam", "0033_alter_attempt_score_alter_option_option1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="option",
            name="option1",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="option",
            name="option2",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="option",
            name="option3",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="option",
            name="option4",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
