# Generated by Django 4.2.2 on 2023-06-19 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("exam", "0036_alter_attempt_score_alter_option_option1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="approvalrequest",
            name="exam",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="app_requests",
                to="exam.exam",
            ),
        ),
    ]
