# Generated by Django 4.2.2 on 2023-06-19 18:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exam", "0037_alter_approvalrequest_exam"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attemptquestion",
            name="selected_option",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="option",
            name="option1",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="option",
            name="option2",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="option",
            name="option3",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="option",
            name="option4",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="option",
            name="text_answer",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("multiple_choice", "Multiple Choice"),
                    ("text_based", "Text Based"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="name",
            field=models.CharField(max_length=20),
        ),
    ]
