# Generated by Django 4.2.2 on 2023-06-20 09:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exam", "0041_alter_approvalrequest_exam_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exam",
            name="end_time",
            field=models.DateTimeField(default="2023-06-20 09:05:12"),
        ),
        migrations.AlterField(
            model_name="exam",
            name="start_time",
            field=models.DateTimeField(default="2023-06-20 09:05:12"),
        ),
    ]
