# Generated by Django 4.2.2 on 2023-06-21 07:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("exam", "0042_alter_exam_end_time_alter_exam_start_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="approvalrequest",
            name="exam",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="exam.exam"
            ),
        ),
        migrations.AlterField(
            model_name="attempt",
            name="exam",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="attempts",
                to="exam.exam",
            ),
        ),
        migrations.AlterField(
            model_name="attempt",
            name="score",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="attempt",
            name="student",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="attemptquestion",
            name="student",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="attempts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="exam",
            name="end_time",
            field=models.DateTimeField(default="2023-06-21 07:56"),
        ),
        migrations.AlterField(
            model_name="exam",
            name="start_time",
            field=models.DateTimeField(default="2023-06-21 07:56"),
        ),
        migrations.AlterField(
            model_name="exam",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="exams",
                to="exam.subject",
            ),
        ),
        migrations.AlterField(
            model_name="exam",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="exams_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("multiple_choice", "Multiple Choice"),
                    ("text_based", "Text Based"),
                ],
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="subject",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="exam.subject",
            ),
        ),
    ]
