# Generated by Django 4.2.2 on 2023-06-21 09:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exam", "0049_remove_exam_questions_count_alter_exam_end_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exam",
            name="end_time",
            field=models.DateTimeField(default="2023-06-21 09:10"),
        ),
        migrations.AlterField(
            model_name="exam",
            name="start_time",
            field=models.DateTimeField(default="2023-06-21 09:10"),
        ),
    ]
