# Generated by Django 4.2.2 on 2023-06-21 12:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exam", "0050_alter_exam_end_time_alter_exam_start_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exam",
            name="end_time",
            field=models.DateTimeField(default="2023-06-21 12:59"),
        ),
        migrations.AlterField(
            model_name="exam",
            name="start_time",
            field=models.DateTimeField(default="2023-06-21 12:59"),
        ),
        migrations.AlterField(
            model_name="option",
            name="text_answer",
            field=models.CharField(max_length=25, null=True),
        ),
    ]
